# Generated by Django 5.2.1 on 2025-10-23 21:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('total_mount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('currency', models.CharField(choices=[('CLP', 'Chilean Peso ($)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)')], default='CLP', max_length=3)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
