# Generated by Django 5.2.1 on 2025-10-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_budgetfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='budget',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
