# Generated by Django 5.2.1 on 2025-10-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_name_budget_title_budget_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='type',
            field=models.CharField(choices=[('1', 'Transferencia Bancaria'), ('2', 'Efectivo'), ('3', 'Orden de Pago'), ('4', 'Debito/Credito')], default='1', max_length=1),
        ),
    ]
