# Generated by Django 5.2.1 on 2025-10-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_budget_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='enable',
        ),
        migrations.AddField(
            model_name='budget',
            name='department',
            field=models.CharField(choices=[('1', 'WOM'), ('2', 'ENTEL'), ('3', 'MOVISTAR'), ('4', 'GALPON')], default='WOM', max_length=32),
        ),
    ]
