# Generated by Django 5.2.1 on 2025-10-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_budget_enable_budget_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='department',
            field=models.CharField(choices=[('1', 'WOM'), ('2', 'ENTEL'), ('3', 'MOVISTAR'), ('4', 'GALPON')], default='1', max_length=32),
        ),
    ]
