# Generated by Django 5.2.1 on 2025-10-26 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_budget_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='total_mount',
            field=models.DecimalField(decimal_places=0, max_digits=24, validators=[django.core.validators.MinValueValidator(0.01, message='Monto debe ser positivo.')]),
        ),
    ]
